# Generated by Django 4.1.1 on 2022-10-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailService', '0002_alter_contactusmodel_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactusmodel',
            old_name='available_data',
            new_name='available_date',
        ),
    ]
